version: '3.6'
services:
  # MySQL and document data store
  database:
    container_name: database
    image: "postgres:latest"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

  # Redis for messaging queue and caching
  queue:
    container_name: queue
    hostname: payercoin_queue
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  # main:
  #   build:
  #     context: .
  #   container_name:  
  #   command: >
  #     bash -c "sleep 15; /usr/bin/supervisord"
  #   restart: on-failure
  #   depends_on:
  #     - payercoin_database
  #     - payercoin_queue
  #   ports:
  #     - "4000:8000"
  #   env_file:
  #     - ./docker.env

volumes:
    database-data:
    redisdata: